services:
  db:
    image: mysql:8.0
    restart: always
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mysql-data:/var/lib/mysql  # Mount the volume for database data persistence
      - ./init.sql:/docker-entrypoint-initdb.d/initdb/init.sql:ro # Ensure correct volume mapping
    ports:
      - "1500:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - app-network


  app:
    build: .  # Build from Dockerfile
    container_name: app_container
    ports:
      - 8080:8080  # Map to Spring Boot's default port

    restart: on-failure
    depends_on:
      - db  # Ensure database starts first
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/booking_manager?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1qaz@WSX3edc
    volumes:
      - logs:/app/logs  # Persist application logs
    networks:
      - app-network

volumes:
  logs:

networks:
  app-network: