name: Spring Boot CI/CD Pipeline
'on':
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: 'mysql:8.0'
        env:
          MYSQL_ROOT_PASSWORD: 1qaz@WSX3edc
          MYSQL_DATABASE: booking_manager
          MYSQL_USER: admin
          MYSQL_PASSWORD: 1qaz@WSX3edc
        ports:
          - '3306:3306'
        options: >-
          --health-cmd="mysqladmin ping" --health-interval=10s
          --health-timeout=5s --health-retries=10
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: '${{ runner.os }}-maven-${{ hashFiles(''**/pom.xml'') }}'
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test

      - name: Run Spring Boot Application
        run: 'mvn spring-boot:run &'

      - name: Verify Application is Running
        run: >
          sleep 30 # Wait for Spring Boot application to start

          if ! curl -s http://localhost:8080/actuator/health | grep
          '"status":"UP"'; then
            echo "Spring Boot application failed to start"
            exit 1
          fi

      - name: Stop Spring Boot Application
        run: |
          kill $(cat spring-boot.pid)
